#!/bin/sh
#
# Copyright (C) 2013 Red Hat Inc.
# Author: Salim Badakhchani <sal@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

# Uncomment to debug script
#set -x

# Check if kojak is installed
INST_FILE="/tmp/install"
if [ ! -f "${INST_FILE}" ]; then
    echo -e "\n# Kojak not installed...please select the installation option before atempting to configure the system"
    exit
fi

# Check if kojak is configured
CFG_FILE="/tmp/config"
if [ -f "${CFG_FILE}" ]; then
    echo -e "\n# Kojak already configured"
    exit
fi

# Check SELinux
STATUS=$(sestatus | grep enabled)
if [ -z $STATUS ]; then
    echo -e "\n# SELinux not enabled..."

else
    echo -e "\n# Configuring SELinux Policiy"
    setsebool -P allow_httpd_anon_write=1
    chcon -R -t public_content_rw_t /mnt/koji/*
fi

# Create tag base
cp -a /root/workspace/kojak /home/koji/workspace && chown -R koji:koji /home/koji/workspace/kojak
su -l koji -c "/home/koji/workspace/kojak/scripts/build/create-tag-base -p CENTOS-6"

service jenkins stop
cp -p /etc/sysconfig/jenkins /etc/sysconfig/jenkins.orig
cat > /tmp/jenkins.patch << 'EOF'
--- /etc/sysconfig/jenkins.orig 2014-06-02 17:19:23.000000000 +0200
+++ /etc/sysconfig/jenkins  2014-06-05 15:22:00.665823455 +0200
@@ -26,7 +26,7 @@
 # Be careful when you change this, as you need to update
 # permissions of $JENKINS_HOME and /var/log/jenkins.
 #
-JENKINS_USER="jenkins"
+JENKINS_USER="koji"

 ## Type:        string
 ## Default:     "-Djava.awt.headless=true"
EOF
patch -p0 < /tmp/jenkins.patch
rm -f /tmp/jenkins.patch

echo -e "# Initialising plugin list..."
while ! timeout 1 bash -c "echo > /dev/tcp/localhost/8080"; do echo -e "# Retrying...please be patient" && sleep 12 ; done
curl -L http://updates.jenkins-ci.org/update-center.json | sed '1d;$d' | \
curl -X POST -H 'Accept: application/json' -d @- http://localhost:8080/updateCenter/byId/default/postBack

# Retrieve jenkins client
wget http://localhost:8080/jnlpJars/jenkins-cli.jar


PLUGINS="git \
openshift-deployer \
delivery-pipeline-plugin \
promoted-builds \
authorize-project \
build-pipeline-plugin \
conditional-buildstep \
copyartifact \
github-api \
github \
ssh-agent \
matrix-project \
koji-plugin \
artifactory \
role-strategy"

java -jar jenkins-cli.jar -s http://localhost:8080 install-plugin ${PLUGINS}

# Configure Jenkins
cp -af overlay/* /var/lib/jenkins
chown -R koji:koji /var/lib/jenkins /var/cache/jenkins /var/log/jenkins

# Restart Jenkins server
service jenkins start

echo -e "\nConfiguration complete...Kojak is AOK"
