#!/bin/sh
#
# Copyright (C) 2013 Red Hat Inc.
# Author: Salim Badakhchani <sal@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

# Uncomment to debug script
#set -x

# Check if kojak is installed
INST_FILE="/tmp/install"
if [ ! -f "${INST_FILE}" ]; then
    echo -e "\n# Kojak not installed...please select the installation option before atempting to configure the system"
    exit
fi

# Check if kojak is configured
CFG_FILE="/tmp/config"
if [ -f "${CFG_FILE}" ]; then
    echo -e "\n# Kojak already configured"
    exit
fi

# Load services configuration
DIR=$(dirname $( cd $(dirname $0) ; pwd -P ))
. $DIR/kojak-functions

eachTool config

echo -e "\nBringing the system up...\n"
eachService restart
touch /tmp/config

echo -e "\nConfiguration complete...Kojak is AOK"
