#!/bin/bash

# Debugging
#set -x

# Declare variable
export PROG="koji"
export USER="koji"
export PRODUCT="rcm-mw-tools"
export ARCH="x86_64"

# Begin Koji configuration
su -l ${USER} -c "

# Configure Koji
${PROG} add-host kojibuilder1.localdomain x86_64
${PROG} add-host-to-channel kojibuilder1.localdomain appliance
${PROG} add-host-to-channel kojibuilder1.localdomain createrepo
${PROG} add-host-to-channel kojibuilder1.localdomain livecd
${PROG} add-host-to-channel kojibuilder1.localdomain maven
${PROG} add-host-to-channel kojibuilder1.localdomain vm
${PROG} grant-permission repo kojira
${PROG} grant-permission build kojibuilder1.localdomain

# Add product tags
${PROG} add-tag ${PRODUCT} --arches ${ARCH} --maven-support --include-all
${PROG} add-tag ${PRODUCT}-candidate --arches ${ARCH} --maven-support --include-all
${PROG} add-tag ${PRODUCT}-override --arches ${ARCH} --maven-support --include-all
${PROG} add-tag ${PRODUCT}-build --arches ${ARCH} --maven-support --include-all
${PROG} add-tag ${PRODUCT}-builddeps --arches ${ARCH} --maven-support --include-all
${PROG} add-tag ${PRODUCT}-todo --arches ${ARCH} --maven-support --include-all

# Add dependency tags
${PROG} add-tag jb-middleware-imports --arches none --maven-support --include-all
${PROG} add-tag mead-import-maven-all --arches none --maven-support --include-all

# Add tag inheritance
${PROG} add-tag-inheritance ${PRODUCT}-candidate ${PRODUCT} --priority 0
${PROG} add-tag-inheritance ${PRODUCT}-override ${PRODUCT}-candidate --priority 0
${PROG} add-tag-inheritance ${PRODUCT}-build ${PRODUCT}-override --priority 0
${PROG} add-tag-inheritance ${PRODUCT}-build ${PRODUCT}-builddeps --priority 5
${PROG} add-tag-inheritance ${PRODUCT}-build jb-middleware-imports --priority 10
${PROG} add-tag-inheritance ${PRODUCT}-build mead-import-maven-all --priority 20
${PROG} add-tag-inheritance ${PRODUCT}-build ${PRODUCT}-todo --priority 40

# Add target
${PROG} add-target ${PRODUCT}-candidate ${PRODUCT}-build ${PRODUCT}-candidate

# Add external repo
${PROG} add-external-repo -t ${PRODUCT}-build centos-mirror http://mirror.centos.org/centos/6/os/x86_64/

# Add groups

# build
${PROG} add-group ${PRODUCT}-build build
${PROG} add-group-pkg ${PRODUCT}-build build bash bzip2 cpio diffutils fedora-release findutils gawk gcc gcc-c++ info make redhat-rpm-config rpm-build sed shadow-utils unzip util-linux-ng which xz

# srpm-build
${PROG} add-group ${PRODUCT}-build srpm-build
${PROG} add-group-pkg ${PRODUCT}-build srpm-build bash curl cvs fedora-release fedpkg gnupg2 make redhat-rpm-config rpm-build shadow-utils

# appliance-build
${PROG} add-group ${PRODUCT}-build appliance-build
${PROG} add-group-pkg ${PRODUCT}-build appliance-build appliance-tools bash coreutils grub parted perl policycoreutils selinux-policy shadow-utils

# maven-build
${PROG} add-group ${PRODUCT}-build maven-build
${PROG} add-group-pkg ${PRODUCT}-build maven-build bash coreutils java-1.7.0-openjdk-devel maven3 subversion liberation-sans-fonts liberation-serif-fonts liberation-mono-fonts git

# livecd-build
${PROG} add-group ${PRODUCT}-build livecd-build
${PROG} add-group-pkg ${PRODUCT}-build livecd-build bash bzip2 coreutils cpio diffutils fedora-logos fedora-release findutils gawk gcc gcc-c++ grep gzip info livecd-tools make patch policycoreutils python-dbus redhat-rpm-config rpm-build sed selinux-policy-targeted shadow-utils squashfs-tools tar unzip util-linux which yum

# wrapper-build
${PROG} add-group ${PRODUCT}-build wrapper-rpm-build
${PROG} add-group-pkg ${PRODUCT}-build wrapper-rpm-build bash redhat-release redhat-release-server redhat-rpm-config rpm-build shadow-utils

# Ramp up capacity
${PROG} edit-host --capacity 10.0 kojibuilder1.localdomain

# Add required build packages
${PROG} add-pkg --owner=kojiadmin ${PRODUCT} bash binutils

# Update kojibuilder record
echo -e 'delete from host_channels where host_id = '1';
delete from host where name = 'kojibuilder1.localdomain';
delete from user_perms where user_id = '4';
delete from users where name = 'kojibuilder1.localdomain';
insert into host (id, user_id, name, arches) values (1, 5, 'kojibuilder1.localdomain', 'x86_64');
insert into host_channels (host_id, channel_id) values (1, 1);
insert into host_channels (host_id, channel_id) values (1, 2);
insert into host_channels (host_id, channel_id) values (1, 3);
insert into host_channels (host_id, channel_id) values (1, 4);
insert into host_channels (host_id, channel_id) values (1, 5);
insert into host_channels (host_id, channel_id) values (1, 6);' > ~/kojibuilder.sql
psql koji koji < /tmp/kojibuilder.sql
rm ~/kojibuilder.sql

# Adding Maven
cd ~
wget http://kojipkgs.fedoraproject.org//packages/maven/3.2.1/5.fc21/src/maven-3.2.1-5.fc21.src.rpm
wget http://kojipkgs.fedoraproject.org//packages/maven/3.2.1/5.fc21/noarch/maven-3.2.1-5.fc21.noarch.rpm
${PROG} import --create-build maven-3.2.1-5.fc21.src.rpm maven-3.2.1-5.fc21.noarch.rpm
${PROG} add-pkg --owner=kojiadmin ${PRODUCT} maven
${PROG} tag-build ${PRODUCT}-candidate maven-3.2.1-5.fc21
rm -f *.rpm
cd -

# Show config
echo -e 'Created the configuration...\n'
${PROG} list-external-repos
${PROG} list-hosts
${PROG} list-tags  
${PROG} list-targets
${PROG} list-tasks
"

# Restart the services
service postgresql restart
service httpd restart
service kojid restart
service kojira restart
