#!/bin/bash

# Debugging
#set -x

# Define product tag
export PRODUCT="jb-ip-6"

# Begin Koji configuration
su -l koji -c "

# Add tags
koji add-tag ${PRODUCT} --arches x86_64 --maven-support --include-all
koji add-tag ${PRODUCT}-candidate --arches x86_64 --maven-support --include-all
koji add-tag ${PRODUCT}-override --arches x86_64 --maven-support --include-all
koji add-tag ${PRODUCT}-build --arches x86_64 --maven-support --include-all
koji add-tag ${PRODUCT}-todo --arches x86_64 --maven-support --include-all

# Add tag inheritance
koji add-tag-inheritance ${PRODUCT}-candidate ${PRODUCT} --priority 0
koji add-tag-inheritance ${PRODUCT}-override ${PRODUCT}-candidate --priority 0
koji add-tag-inheritance ${PRODUCT}-build ${PRODUCT}-override --priority 0
koji add-tag-inheritance ${PRODUCT}-build ${PRODUCT}-todo --priority 40

# Add target
koji add-target ${PRODUCT}-candidate ${PRODUCT}-build ${PRODUCT}-candidate

# Add external repo
koji add-external-repo -t ${PRODUCT}-build centos-mirror http://mirror.centos.org/centos/6/os/x86_64/

# Add groups

# build
koji add-group ${PRODUCT}-build build
koji add-group-pkg ${PRODUCT}-build build bash bzip2 cpio diffutils fedora-release findutils gawk gcc gcc-c++ info make redhat-rpm-config rpm-build sed shadow-utils unzip util-linux-ng which xz

# srpm-build
koji add-group ${PRODUCT}-build srpm-build
koji add-group-pkg ${PRODUCT}-build srpm-build bash curl cvs fedora-release fedpkg gnupg2 make redhat-rpm-config rpm-build shadow-utils

# appliance-build
koji add-group ${PRODUCT}-build appliance-build
koji add-group-pkg ${PRODUCT}-build appliance-build appliance-tools bash coreutils grub parted perl policycoreutils selinux-policy shadow-utils

# maven-build
koji add-group ${PRODUCT}-build maven-build
koji add-group-pkg ${PRODUCT}-build maven-build bash coreutils java-1.7.0-openjdk-devel maven3 subversion liberation-sans-fonts liberation-serif-fonts liberation-mono-fonts git

# livecd-build
koji add-group ${PRODUCT}-build livecd-build
koji add-group-pkg ${PRODUCT}-build livecd-build bash bzip2 coreutils cpio diffutils fedora-logos fedora-release findutils gawk gcc gcc-c++ grep gzip info livecd-tools make patch policycoreutils python-dbus redhat-rpm-config rpm-build sed selinux-policy-targeted shadow-utils squashfs-tools tar unzip util-linux which yum

# wrapper-build
koji add-group ${PRODUCT}-build wrapper-rpm-build
koji add-group-pkg ${PRODUCT}-build wrapper-rpm-build bash redhat-release redhat-release-server redhat-rpm-config rpm-build shadow-utils

# Ramp up capacity
koji edit-host --capacity 10.0 kojibuilder1

# Add required build packages
koji add-pkg --owner=kojiadmin ${PRODUCT} bash binutils

# List created tags
echo -e "Created the following tags...\n"
koji list-tags
"
