#!/bin/bash

# Debugging
#set -x

# Declare variable
export PROG="koji"
export USER="koji"
export PRODUCT="jb-ip-6"

# Begin Koji configuration
su -l ${USER} -c "

# Add tags
${PROG} add-tag ${PRODUCT} --arches x86_64 --maven-support --include-all
${PROG} add-tag ${PRODUCT}-candidate --arches x86_64 --maven-support --include-all
${PROG} add-tag ${PRODUCT}-override --arches x86_64 --maven-support --include-all
${PROG} add-tag ${PRODUCT}-build --arches x86_64 --maven-support --include-all
${PROG} add-tag ${PRODUCT}-todo --arches x86_64 --maven-support --include-all
${PROG} add-tag jb-middleware-imports --arches none --maven-support --include-all

# Add tag inheritance
${PROG} add-tag-inheritance ${PRODUCT}-candidate ${PRODUCT} --priority 0
${PROG} add-tag-inheritance ${PRODUCT}-override ${PRODUCT}-candidate --priority 0
${PROG} add-tag-inheritance ${PRODUCT}-build ${PRODUCT}-override --priority 0
${PROG} add-tag-inheritance ${PRODUCT}-build jb-middleware-imports --priority 10
${PROG} add-tag-inheritance ${PRODUCT}-build ${PRODUCT}-todo --priority 40

# Add target
${PROG} add-target ${PRODUCT}-candidate ${PRODUCT}-build ${PRODUCT}-candidate

# Add external repo
${PROG} add-external-repo -t ${PRODUCT}-build centos-mirror http://mirror.centos.org/centos/6/os/x86_64/

# Add groups

# build
${PROG} add-group ${PRODUCT}-build build
${PROG} add-group-pkg ${PRODUCT}-build build bash bzip2 cpio diffutils fedora-release findutils gawk gcc gcc-c++ info make redhat-rpm-config rpm-build sed shadow-utils unzip util-linux-ng which xz

# srpm-build
${PROG} add-group ${PRODUCT}-build srpm-build
${PROG} add-group-pkg ${PRODUCT}-build srpm-build bash curl cvs fedora-release fedpkg gnupg2 make redhat-rpm-config rpm-build shadow-utils

# appliance-build
${PROG} add-group ${PRODUCT}-build appliance-build
${PROG} add-group-pkg ${PRODUCT}-build appliance-build appliance-tools bash coreutils grub parted perl policycoreutils selinux-policy shadow-utils

# maven-build
${PROG} add-group ${PRODUCT}-build maven-build
${PROG} add-group-pkg ${PRODUCT}-build maven-build bash coreutils java-1.7.0-openjdk-devel maven3 subversion liberation-sans-fonts liberation-serif-fonts liberation-mono-fonts git

# livecd-build
${PROG} add-group ${PRODUCT}-build livecd-build
${PROG} add-group-pkg ${PRODUCT}-build livecd-build bash bzip2 coreutils cpio diffutils fedora-logos fedora-release findutils gawk gcc gcc-c++ grep gzip info livecd-tools make patch policycoreutils python-dbus redhat-rpm-config rpm-build sed selinux-policy-targeted shadow-utils squashfs-tools tar unzip util-linux which yum

# wrapper-build
${PROG} add-group ${PRODUCT}-build wrapper-rpm-build
${PROG} add-group-pkg ${PRODUCT}-build wrapper-rpm-build bash redhat-release redhat-release-server redhat-rpm-config rpm-build shadow-utils

# Ramp up capacity
${PROG} edit-host --capacity 10.0 ${PROG}builder1

# Add required build packages
${PROG} add-pkg --owner=${PROG}admin ${PRODUCT} bash binutils

# List created tags
echo -e 'Created the following tags...\n'
${PROG} list-tags

# Adding Maven
cd /tmp
wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-6/SRPMS/apache-maven-3.2.1-1.el6.src.rpm
wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-6/x86_64/apache-maven-3.2.1-1.el6.noarch.rpm
${PROG} import --create-build /tmp/apache-maven-3.2.1-1.el6.src.rpm /tmp/apache-maven-3.2.1-1.el6.noarch.rpm
${PROG} add-pkg --owner=kojiadmin jb-ip-6 apache-maven
${PROG} tag-build jb-ip-6-candidate apache-maven-3.2.1-1.el6
rm -rf apache*
cd -
"
