#!/bin/bash
#
# Simple script to install openshift

echo -e "# Installing packages"
rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm
yum install -y puppet ruby
gem install --no-rdoc rhc

if [ ! -f "~/.openshift/oo-install-cfg.yml" ]; then
  mkdir ~/.openshift
  cp ~/workspace/kojak/scripts/config/oo-install-cfg.yml ~/.openshift
fi

echo -e "# Installing Openshift"
echo -e "1\n3\nn\nn" > /tmp/response.txt
sh <(curl -s https://install.openshift.com/origin-m4) < /tmp/response.txt

echo -e "# Installing rhc tools"
gem install rhc
echo -e "\n\ny\ndemo\nopenshift\ny\ny\nn" > /tmp/response.txt
rhc setup < /tmp/response.txt

echo -e "# Configuring domains for development, testing and production"
rhc domain create -n development
rhc domain create -n testing
rhc domain create -n production

echo -e "# Install packages required for demo and activate cartridges"
yum -y install https://s3-us-west-2.amazonaws.com/getup-mirror/getup-openshift-origin-release-4/dependencies/tomcat6-6.0.39-1.noarch.rpm \
https://s3-us-west-2.amazonaws.com/getup-mirror/getup-openshift-origin-release-4/dependencies/tomcat7-7.0.50-1.noarch.rpm \
https://s3-us-west-2.amazonaws.com/getup-mirror/getup-openshift-origin-release-4/dependencies/maven3-3.0.3-4.noarch.rpm \
https://s3-us-west-2.amazonaws.com/getup-mirror/getup-openshift-origin-release-4/dependencies/jboss-as7-modules-7.1.1.Final-1.noarch.rpm \
https://s3-us-west-2.amazonaws.com/getup-mirror/getup-openshift-origin-release-4/dependencies/jboss-as7-7.1.1.Final-1.noarch.rpm \
openshift-origin-cartridge-jbossas \
openshift-origin-cartridge-jbossews

echo -e "# Restarting cloud services" 
service ruby193-mcollective restart

echo -e "# Activating catridges"
oo-admin-ctl-cartridge -c import-node --activate
