#!/bin/bash
#
# Copyright (C) 2013 Red Hat Inc.
# Author: Salim Badakhchani <sal@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

# Uncomment to debug script
#set -x

# Declare default configuration options

# Distro information
VMNAME=${VMNAME:="broker-CentOS-6.6-x86_64"}
VMHOME=${VMHOME:="/var/lib/libvirt/images"}
TMPDIR=${TMPDIR:="${HOME}/broker"}
DISTDIR=${DISTDIR:="CentOS/6.6/x86_64"}
# Sources and configuration
CFGDIR=${CFGDIR:="${TMPDIR}/cfg/${DISTDIR}"}
KSCFG=${KSCFG:="${CFGDIR}/broker-ks.cfg"}
KJKCFG=${KJKCFG:="${CFGDIR}/broker.cfg"}
SRCLOC=${SRCLOC:="http://mirror.centos.org/centos/6/os/x86_64/"}

# Virtual machine specifications
OS_TYPE=${OS_TYPE:="linux"}
OS_VARIANT=${OS_VARIANT:="rhel6"}
ARCH=${ARCH:="x86_64"}
VCPU=${VCPU:="2"}
VMMEM=${VMMEM:="4096"}
VMDISK=${VMDISK:="8192M"}

# Check user priviledges
if [ "$USER" != "root" ]; then
    echo -e "\n# This script requires root priviledges to run"
exit
fi

APPNAME="broker"

VMDOMAIN=$(virsh list --all | grep ${APPNAME} | awk '{print $(NF-2)}')
if [ ! "${VMDOMAIN}" ]; then
    echo -e "# No pre-existing broker"
else 
    while true; do
    read -p "# Found an existing VM with the same name...Do you want to destroy it?`echo $'\n>> '` [Y/n] " yn
    case $yn in
        [Yy]* ) virsh undefine ${VMNAME} && virsh destroy ${VMNAME} && virsh vol-delete --pool default ${VMNAME}.img > /dev/null 2>&1
    break
    ;;
        [Nn]* ) menu
    ;;
        * ) echo ">> Invalid Option";;
    esac
    done
fi

echo -e "# Restarting Virtualization"
sudo service libvirtd restart > /dev/null 2>&1

echo -e "# Allocating Diskspace"
sudo fallocate -l ${VMDISK} ${VMHOME}/${VMNAME}.img

echo -e "# Installating Packages\n"
virt-install \
-n ${VMNAME} \
--accelerate \
--ram ${VMMEM} \
--vcpus ${VCPU} \
--os-type ${OS_TYPE} \
--os-variant ${OS_VARIANT} \
--arch ${ARCH} \
--disk ${VMHOME}/${VMNAME}.img \
--initrd-inject "${KSCFG}" \
--location ${SRCLOC} \
--extra-args "ks=file:/$(basename ${KSCFG}) console=tty0 console=ttyS0,115200 serial rd_NO_PLYMOUTH" \
--console pty \
--nographics
exit
}

