#!/bin/bash
#
# Kojak installation removal

# Debugging
#set -x

# Check to see if user is root
if [ "${USER}" != "root" ]; then
    echo -e "\n# This script requires root priviledges to run"
    exit
fi

# Remove package
yum -y remove httpd postgresql-server koji koji-hub koji-web koji-utils koji-hub-plugins koji-vm koji-builder

CFG_DIRS="/var/tmp/kojak /mnt/koji /etc/koji* /etc/httpd /var/log/httpd /etc/pki/koji /tmp/*.patch /var/lib/pgsql"
for dir in ${CFG_DIRS}; do rm -rf $dir || echo "$dir not found"; done

LOG_FILES="/var/log/kojira.log
/var/log/kojid.log
${HOME}/kickstart.log
${HOME}/kojak.log
/etc/profile.d/custom.sh
/etc/yum.repos.d/rhel6-koji.repo"
for file in ${LOG_FILES}; do rm -f $file || echo "$file not found"; done

# Remove user koji user
userdel -r koji

# Update mlocate database
cd /
updatedb
ORIG_FILES=$(locate *.orig)
for file in ${ORIG_FILES}; do cat $file > $(echo $file | sed "s/\.orig$//") && rm -f $file || echo "$file not found"; done

updatedb

