#!/bin/bash
#
# Copyright (C) 2013 Red Hat Inc.
# Author: Salim Badakhchani <sal@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

# Uncomment to debug script
#set -x

# Check to see if user is root
if [ "${USER}" != "root" ]; then
    echo -e "\n# This script requires root priviledges to run"
    exit
fi

# Remove koji user
userdel -rf koji
groupdel koji

# Stop services
chkconfig postgresql off
service postgresql stop
chkconfig httpd off 
service httpd stop
chkconfig kojid off
service kojid stop
chkconfig kojira off
service kojira stop

# Remove package
yum -y remove httpd postgresql-server koji koji-hub koji-web koji-utils koji-hub-plugins koji-vm koji-builder mock jenkins

# Remove Jenkins repo
rm -f /etc/yum.repos.d/jenkins.repo.*

# Remove configuration files
CFG_DIRS="/var/tmp/kojak /mnt/koji /etc/koji* /home/koji /etc/httpd /var/log/httpd /etc/pki/koji /tmp/*.patch /var/lib/pgsql /var/lib/mock /var/lib/jenkins /var/cache/jenkins /etc/init.d/aprox"
for dir in ${CFG_DIRS}; do rm -rf $dir || echo "$dir not found"; done

# Remove log files
LOG_FILES="/var/log/kojira.log
/var/log/kojid.log
${HOME}/kickstart.log
${HOME}/kojak.log
/etc/profile.d/custom.sh
/etc/yum.repos.d/epel.repo"
for file in ${LOG_FILES}; do rm -f $file || echo "$file not found"; done

# Update mlocate database
echo -e "\nUpdating file datatabse...please be paitient."
cd /
updatedb
ORIG_FILES=$(locate *.orig)
for file in ${ORIG_FILES}; do cat $file > $(echo $file | sed "s/\.orig$//") && rm -f $file || echo "$file not found"; done
updatedb
echo -e "Uninstalltion complete."
