#!/bin/bash
# 
# Copyright (C) 2013 Red Hat Inc.
# Author: Salim Badakhchani <sal@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>. 
#
########################################################################

# Uncomment to debug script
#set -x

# Check to see if user is root
if [ "$USER" != "root" ]; then
    echo -e "\n# This script requires root priviledges to run"
    exit
fi

reset

SCRIPTS="`pwd`/scripts"

welcome_header() {
    clear
    echo -e "\n################################################################################"
    echo -e "#                                                                              #"
    echo -e "#                   !!! Welcome to Kojak...Koji in a box !!!                   #"
    echo -e "#                                                                              #\n"
}

menu_msg_01() {
    echo -e ">> Select the type of installation from the menu options below."
}

menu () {
PS3='Please Select installation type: '
echo
options=("Virtual" "Local" "Remove install" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Virtual")
            echo "Virtual Installation Selected "
            $SCRIPTS/virtual-install
            exit
            ;;
        "Local")
            echo "Local Installation Selected "
            $SCRIPTS/local-install
            exit
            ;;
        "Remove install")
            echo "Remove Installation Selected "
            $SCRIPTS/remove-install
            exit
            ;;
        "Quit")
            break
            ;;
        *) echo -e ">> Invalid Option"
            ;;
    esac
done
}

welcome_header
menu_msg_01
menu
