#!/bin/bash
#
# Simple script to initate Koji installation type

heading() {
    clear
    echo -e "\n################################################################################"
    echo -e "#                                                                              #"
    echo -e "#                   !!! Welcome to Kojak...Koji in a box !!!                   #"
    echo -e "#                                                                              #\n"
}

menu() {
    while true
    do
    # Determin installation type
    heading
        read -s -n1 -p "`echo $'\n>> '`Press [RETURN] or [SPACE] for a virtual installation. `echo $'\n>> '`Press any other key for a local installation. `echo $'\n>> '`Press [CTRL-C] to exit." KEY
        if [ ${#KEY} -eq "0" ]; then
            echo -e "\n\n# Conducting a virtual installation."
            virtual-install.sh
        else
            echo -e "\n\n# Conducting a local installation"
            local-install.sh
        fi
    done
}

menu
