#!/bin/bash
#
# Simple script to backup jenkins

# Uncommet for debugging
#set -x

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

JENKINS_HOME="/var/lib/jenkins/"
DATE=$(date "+%Y%m%d-%M%S")

[ -d /tmp/backup ] || mkdir -p /tmp/backup

tar zcfvp /tmp/backup/jenkins.${DATE}.tar.gz /var/lib/jenkins
mkdir /tmp/overlay.${DATE}
cd /tmp/overlay.*
cp /var/lib/jenkins/*.xml .
cp -a /var/lib/jenkins/jobs/ /var/lib/jenkins/users/ .
find . -name "builds" -type d -exec rm -rf {} +
find . -name "workspace" -type d -exec rm -rf {} +
cd ..
mv /tmp/overlay.* /tmp/backup/
