#!/bin/bash
#
# Simple script to re-initialise the koji database

# Debugging
set -x

# Declare variable
export PROG="koji"
export USER="koji"
export PRODUCT="rcm-mw-tools"
export ARCH="x86_64"
export MAVEN="maven3-3.0.3-4"

# Check to see if user is root
if [ "$USER" != "root" ]; then
echo -e "\n# This script requires root priviledges to run"
    exit
fi

# Clear the koji directories
service kojid stop
service kojira stop
rm -rf /mnt/koji
mkdir /mnt/koji
cd /mnt/koji
mkdir {packages,repos,work,scratch}
chown -R apache.apache *
> /var/log/kojid.log
> /var/log/kojira.log

# Re-install database
yum -y remove postgresql-server
rm -rf /var/lib/pgsql
yum -y install postgresql-server
postgresql-setup initdb
systemctl enable postgresql.service
systemctl start postgresql.service

# /tmp/users.sql
echo -e "insert into users (name, status, usertype) values ('koji', 0, 0);
insert into user_perms (user_id, perm_id, creator_id) values (1, 1, 1);
insert into users (name, status, usertype) values ('kojiadmin', 0, 0);
insert into user_perms (user_id, perm_id, creator_id) values (2, 1, 1);
\q" >> /tmp/users.sql

# /var/lib/pgsql/data/postgresql.conf
cp -p /var/lib/pgsql/data/postgresql.conf /var/lib/pgsql/data/postgresql.conf.orig
sed -i -e "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /var/lib/pgsql/data/postgresql.conf

# /var/lib/pgsql/data/pg_hba.conf
cp /var/lib/pgsql/data/pg_hba.conf /var/lib/pgsql/data/pg_hba.conf.orig

echo -e "
# Koji
local koji koji trust
local koji apache trust
host koji koji 127.0.0.1/32 trust
host koji apache 127.0.0.1/32 trust
host koji koji ::1/128 trust
host koji apache ::1/128 trust
host koji koji 10.34.25.167/32 trust
host koji apache 10.34.25.167/32 trust" >> /var/lib/pgsql/data/pg_hba.conf

sed -i -e "s/local all all peer/local all all trust/g" /var/lib/pgsql/data/pg_hba.conf
chown postgres:postgres /var/lib/pgsql/data/pg_hba.conf.orig

# Create the database tables
su -l postgres -c "createuser koji; createdb -O koji koji"
su -l koji -c "psql koji koji < /usr/share/doc/koji/docs/schema.sql"
su -l koji -c "psql koji koji < /tmp/users.sql"

# Restart database services
systemctl restart postgresql.service
systemctl restart httpd.service

# Begin Koji configuration
su -l ${USER} -c "

# Configure Koji
${PROG} add-host kojibuilder1.localdomain x86_64
${PROG} add-host-to-channel kojibuilder1.localdomain appliance
${PROG} add-host-to-channel kojibuilder1.localdomain createrepo
${PROG} add-host-to-channel kojibuilder1.localdomain livecd
${PROG} add-host-to-channel kojibuilder1.localdomain maven
${PROG} add-host-to-channel kojibuilder1.localdomain vm
${PROG} grant-permission repo kojira
${PROG} grant-permission build kojibuilder1.localdomain

# Add product tags
${PROG} add-tag ${PRODUCT} --arches ${ARCH} --maven-support --include-all
${PROG} add-tag ${PRODUCT}-candidate --arches ${ARCH} --maven-support --include-all
${PROG} add-tag ${PRODUCT}-build --arches ${ARCH} --maven-support --include-all

# Add tag inheritance
${PROG} add-tag-inheritance ${PRODUCT}-candidate ${PRODUCT} --priority 0
${PROG} add-tag-inheritance ${PRODUCT}-build ${PRODUCT}-candidate --priority 0

# Add target
${PROG} add-target ${PRODUCT}-candidate ${PRODUCT}-build ${PRODUCT}-candidate

# Add external repo
${PROG} add-external-repo -t ${PRODUCT}-build centos-mirror http://mirror.centos.org/centos/6/os/x86_64/

# Add groups
# build
${PROG} add-group ${PRODUCT}-build build
${PROG} add-group-pkg ${PRODUCT}-build build bash bzip2 cpio diffutils fedora-release findutils gawk gcc gcc-c++ info make redhat-rpm-config rpm-build sed shadow-utils unzip util-linux-ng which xz

# srpm-build
${PROG} add-group ${PRODUCT}-build srpm-build
${PROG} add-group-pkg ${PRODUCT}-build srpm-build bash curl cvs fedora-release fedpkg gnupg2 make redhat-rpm-config rpm-build shadow-utils

# appliance-build
${PROG} add-group ${PRODUCT}-build appliance-build
${PROG} add-group-pkg ${PRODUCT}-build appliance-build appliance-tools bash coreutils grub parted perl policycoreutils selinux-policy shadow-utils

# maven-build
${PROG} add-group ${PRODUCT}-build maven-build
${PROG} add-group-pkg ${PRODUCT}-build maven-build bash coreutils java-1.7.0-openjdk-devel maven3 subversion liberation-sans-fonts liberation-serif-fonts liberation-mono-fonts git

# livecd-build
${PROG} add-group ${PRODUCT}-build livecd-build
${PROG} add-group-pkg ${PRODUCT}-build livecd-build bash bzip2 coreutils cpio diffutils fedora-logos fedora-release findutils gawk gcc gcc-c++ grep gzip info livecd-tools make patch policycoreutils python-dbus redhat-rpm-config rpm-build sed selinux-policy-targeted shadow-utils squashfs-tools tar unzip util-linux which yum

# wrapper-build
${PROG} add-group ${PRODUCT}-build wrapper-rpm-build
${PROG} add-group-pkg ${PRODUCT}-build wrapper-rpm-build bash redhat-release redhat-release-server redhat-rpm-config rpm-build shadow-utils

# Ramp up capacity
${PROG} edit-host --capacity 10.0 kojibuilder1.localdomain

# Add required build packages
${PROG} add-pkg --owner=kojiadmin ${PRODUCT} bash binutils

# Adding Maven
if [ -d "/opt/kojak" ]; then
    ${PROG} import --create-build /opt/kojak/pkgs/${MAVEN}.src.rpm /opt/kojak/pkgs/${MAVEN}.noarch.rpm
    ${PROG} add-pkg --owner=kojiadmin ${PRODUCT} maven3
    ${PROG} tag-build ${PRODUCT}-candidate ${MAVEN}
else
    git clone https://github.com/sbadakhc/kojak.git ~/workspace/kojak
    ${PROG} import --create-build ~/workspace/kojak/pkgs/${MAVEN}.src.rpm ~/workspace/kojak/pkgs/${MAVEN}.noarch.rpm
    ${PROG} add-pkg --owner=kojiadmin ${PRODUCT} maven3
    ${PROG} tag-build ${PRODUCT}-candidate ${MAVEN}
fi
"
# Grant permissions
su -l koji -c "koji grant-permission repo kojira"
su -l koji -c "koji grant-permission build kojibuilder1.localdomain"

# Install Maven3
MVNRPM=$(rpm -q maven3)
if [ ! -z ${MVNRPM} ]; then
        echo -e "${MVNRPM} already installed"
else
        yum -y localinstall /opt/kojak/pkgs/maven3-3.0.3-4.noarch.rpm 
fi

# Restart Koji services
systemctl enable httpd.service
systemctl restart httpd.service
systemctl enable kojid.service
systemctl restart kojid.service
systemctl enable kojira.service
systemctl restart kojira.service
