#!/bin/sh

# Find the dirname of this script
DIR=$(dirname $0)

# Bootstrap the list with the base managed services for kojak
SERVICES=$(cat $DIR/base-managed-services.lst)

# For each file in $DIR/services.d, read the list of managed services from it 
# and concatenate with existing $SERVICES
SERVICES_D="$DIR/services.d"
if [ -d $SERVICES_D ]; then
  for svc in $(ls -1 $SERVICES_D/*); do
    SERVICES = "$SERVICES $(cat $SERVICES_D/$svc)"
  done
fi

# De-dupe managed services in case there's overlap
SERVICES=$(echo $SERVICES | tr " " "\n" | uniq)

#for s in $SERVICES; do
#  echo $s
#done

export SERVICES
