#!/bin/sh

function loadServices {
  # Find the dirname of this script
  DIR=$(dirname $( cd $(dirname $0) ; pwd -P ))

  # Bootstrap the list with the base managed services for kojak
  SERVICES=$(cat $DIR/base-managed-services.lst)
  
  # For each file in $DIR/services.d, read the list of managed services from it 
  # and concatenate with existing $SERVICES
  SERVICES_D="$DIR/services.d"
  if [ -d $SERVICES_D ]; then
    for svc in $(ls -1 $SERVICES_D/*); do
      SERVICES="$SERVICES $(cat $svc)"
    done
  fi

  # De-dupe managed services in case there's overlap
  SERVICES=$(echo $SERVICES | tr " " "\n" | uniq)

  export SERVICES
}

