#!/bin/sh

DIR=$(dirname $0)
export SERVICES=/tmp/kojak-managed-services.d

if [ ! -d $SERVICES ]
then
  mkdir -p $SERVICES
  for svc in $(cat $DIR/base-managed-services.lst)
  do
    touch $SERVICES/$svc
  done
fi

