#!/bin/sh

function eachService {
    # Find the dirname of this script
    DIR=$(dirname $( cd $(dirname $0) ; pwd -P ))
      
    # Bootstrap the list with the base managed services for kojak
    SERVICES=$(cat $DIR/base-managed-services.lst)
      
    # For each $DIR/tools/*/managed-services, read the list of managed services
    # and append to existing $SERVICES
    for svc in $(ls -1 $DIR/tools/*/managed-services 2>/dev/null); do
        SERVICES="$SERVICES $(cat $svc)"
    done

    # De-dupe managed services in case there's overlap
    SERVICES=$(echo $SERVICES | tr " " "\n" | uniq)

    for svc in $SERVICES
    do
        svc=$(basename $svc)
        case "$1" in
            on|off)
                chkconfig $svc $1
                ;;
            start|stop|restart|status)
                service $svc $1
                ;;
        esac
    done
}

function eachTool {
    for script in $(ls -1 $DIR/tools/*/$1 2>/dev/null)
    do
        sh $script
    done
}

