#!/bin/bash

set -x

# Check to see if user is root
if [ "$USER" != "root" ]; then
    echo -e "\n# This script requires root priviledges to run"
    exit
fi

service kojid stop
service kojira stop

# Create koji build directories
rm -rf /mnt/koji
mkdir /mnt/koji
cd /mnt/koji
mkdir {packages,repos,work,scratch}
chown apache.apache *
cd -

> /var/log/kojid.log
> /var/log/kojira.log

psql -U koji -f kojak_db

service postgresql restart
service kojid start
service kojira start
