#!/bin/bash
#
# Simple script to re-initialise the koji database

# Debugging
set -x

# Check to see if user is root
if [ "$USER" != "root" ]; then
    echo -e "\n# This script requires root priviledges to run"
    exit
fi

# Remove package
yum -y remove httpd mod_ssl openssl postgresql-server mod_wsgi yum-utils \
rpm-build createrepo git pyOpenSSL python-krbV python-cheetah cvs svn \
postgresql-python python-qpid libvirt-python qemu-img mod_auth_kerb \
wget screen vim tree links dos2unix mlocate java-1.7.0-openjdk-devel virt-install \
koji koji-hub koji-web koji-utils koji-hub-plugins koji-vm koji-builder

# Revert previous configuration files
cat /etc/hosts.orig > /etc/hosts && rm /etc/hosts.orig
cat /etc/sudoers.orig > /etc/sudoers && rm /etc/sudoers.orig
cat /etc/vimrc.orig > /etc/vimrc && rm /etc/vimrc.orig
cat /etc/httpd/conf.d/ssl.conf.orig > /etc/httpd/conf.d/ssl.conf && rm /etc/httpd/conf.d/ssl.conf.orig
cat /etc/security/limits.conf.orig > /etc/security/limits.conf && rm /etc/security/limits.conf.orig

# Remove files koji related configuration files
rm -rf /mnt/koji
rm /var/log/kojid.log
rm /var/log/kojira.log
rm -rf /etc/httpd/conf.d/koji*
rm -rf /etc/koji*
rm -rf /etc/httpd
rm -rf /etc/pki/koji
rm -rf /var/lib/pgsql

# Remove user koji user
userdel -r koji

# Update mlocate database
updatedb
locate *.orig

