#!/bin/sh

# Installing Jenkins Plugins"
cd /tmp

# Initialise plugin list
curl  -L http://updates.jenkins-ci.org/update-center.json | sed '1d;$d' | curl -X POST -H 'Accept: application/json' -d @- http://localhost:8080/updateCenter/byId/default/postBack

# Retrieve plugins
wget http://localhost:8080/jnlpJars/jenkins-cli.jar
java -jar jenkins-cli.jar -s http://localhost:8080 install-plugin git
java -jar jenkins-cli.jar -s http://localhost:8080 install-plugin koji-plugin

rm -f default.js* jenkins-cli.jar
cd -
service jenkins stop
cp -p /etc/sysconfig/jenkins /etc/sysconfig/jenkins.orig
cat > /tmp/jenkins.patch << 'EOF'
--- /etc/sysconfig/jenkins.orig 2014-06-02 17:19:23.000000000 +0200
+++ /etc/sysconfig/jenkins  2014-06-05 15:22:00.665823455 +0200
@@ -26,7 +26,7 @@
 # Be careful when you change this, as you need to update
 # permissions of $JENKINS_HOME and /var/log/jenkins.
 #
-JENKINS_USER="jenkins"
+JENKINS_USER="koji"

 ## Type:        string
 ## Default:     "-Djava.awt.headless=true"
EOF
patch -p0 < /tmp/jenkins.patch
rm -f /tmp/jenkins.patch

dir=$( cd $(dirname $0) ; pwd -P )
files="${dir}/files"

echo "Copying jenkins overlay files from ${files}/jenkins/* to /var/lib/jenkins..."
cp -af $files/jenkins/* /var/lib/jenkins
mkdir -p /var/lib/jenkins/.pki/nssdb

javaver=$(java -version 2>&1 | head -1 | awk '{print $3}')
javaver="${javaver%\"}"
javaver="${javaver#\"}"

mkdir -p /var/lib/jenkins/.java/fonts/${javaver}

echo "Setting up font config in /var/lib/jenkins/.java/fonts/${javaver}..."
cp $files/fcinfo* /var/lib/jenkins/.java/fonts/${javaver}

chown -R koji:koji /var/lib/jenkins /var/cache/jenkins /var/log/jenkins

service jenkins start

